Bugfix/fix button
dbcls/RefEx2 pull request #13
Opened 2022-04-11 06:19 UTC by gstein314

ボタンやタブのhoverを修正しました。
お手すきの際にご確認お願いします。

2022-04-13 00:45 UTC, MarleenEliza requested changes
@gstein314 ありがとうございます！
CSSの整理もありがとうございます！

コメントを付けましたのでご確認くさい。後、全体的に簡単なTransformのアニメーションを入れても良いかもしれないと思いました。BRCみたいな複雑なアニメーションは必要なくて、ただ色が切り替える時の簡単なTransformがあるともう少し目に優しいかもしれません。

2022-04-13 00:45 UTC, MarleenEliza commented on components/search/SpeciesNavigation.vue
> +                  color: $COLOR_9
この色で少し全体的なデザインが崩れる気がします。Exampleのボタンと同様なデザインで試すのはどうでしょうか？（背景がMAIN _COLORでテキストがWhite）
<img width="219" alt="image" src="https://user-images.githubusercontent.com/62828450/163075701-ea0f498d-1787-4f84-a7da-273f44738360.png">

2022-04-13 00:45 UTC, MarleenEliza commented on assets/css/mixin.sass
> +    background: $BUTTON_HOVER_COLOR
ボタンがHoverされている時とそうではない時の差がもう少し目立てもいい気がしますが、一応金曜日の会議で永野さんとご相談しましょう。

2022-04-13 04:00 UTC, gstein314 commented on components/search/SpeciesNavigation.vue
> +                  color: $COLOR_9
ご確認ありがとうございます。こちらのデザイン修正してみます。

2022-04-18 05:37 UTC, gstein314 commented
ボタンをhoverした時の色を変更しました。

2022-04-19 07:36 UTC, MarleenEliza approved these changes
ありがとうございます！

良いと思います。Transformが逆観遅いかもしれませんが、一応このブランチをマージさせていただきます。金曜日に永野さんのご意見も聞く予定です。

2022-04-19 07:36 UTC, merged