add error alert
dbcls/RefEx2 pull request #14
Opened 2022-04-20 06:44 UTC by gstein314

エラーアラート画面を追加しました。
表示するメッセージに違和感があるかもしれませんので、その点もご確認ください。
テスト後、以下コメント文がある箇所のボタンを除去する必要があります。
TODO: remove after testing

お手すきの際にご確認をお願いします。

2022-04-21 05:45 UTC, MarleenEliza requested changes

2022-04-21 05:45 UTC, MarleenEliza commented on components/ModalView/ModalViewGene.vue
>              console.log(error);
エラーメッセージを入れたところでConsole.logを消してOKです！もし`error`の変数を使わないことで怒られたらerrorの前に_をつけてみてください。(参考：https://www.w3schools.com/js/js_variables.asp　JavaScript underscoreのところ)

2022-04-21 05:45 UTC, MarleenEliza commented on components/ModalView/ModalViewAlert.vue
> +    color: $BLACK
コード的には問題ないと思いますが、デザインに関しては永野さんとご相談していただけますでしょうか？金曜日の会議に詳しく話しましょう。

2022-04-21 05:45 UTC, MarleenEliza commented on components/search/SearchBar.vue
>              console.log(err);
他のファイルと同様

2022-04-21 05:45 UTC, MarleenEliza commented on components/ScreenerView/ScreenerViewSample.vue
>              console.log('error', error);
他のファイルと同様

2022-04-21 05:46 UTC, MarleenEliza commented
対応ありがとうございます！基本的にOKと思いますが、細かいところはコメントでご確認ください。
また、Devブランチが更新されたので最新版とのConflictを解決していただけますでしょうか？もしConflictの解決方法を一人でよく判断できなかったらお知らせください！

2022-04-21 09:18 UTC, gstein314 commented
@MarleenEliza 
レビューありがとうございます。Conflict解決しました。
デザインに関しては金曜日に改めてご相談させてください。

2022-04-22 07:50 UTC, gstein314 commented
永野さんからご指摘のあったエラー用のカラーを追加しました。

2022-04-22 08:00 UTC, gstein314 commented
タブをhoverしたときの色を修正しました。

2022-04-26 02:18 UTC, MarleenEliza requested changes
お疲れ様です！私が前回のコードレビューで見落とした点があったみたいでその修正だけをお願いしたいと思います。今更ですみません。

2022-04-26 02:18 UTC, MarleenEliza commented on components/ModalView/ModalViewGene.vue
> +            });
この間のレビューで見落としましたが、この場合は必ず`this.`を指定する必要があります。`Store`を呼ぶメソッドもVue component内にしか存在していないからです。
また、...mapMutationsでメソッドを一回定義した方が良いかもしれません。
つまり、エラーのCatchが以下となります：
```suggestion
            this.setAlertModal({msg: 'Failed to get data in Modal View Gene'});
```

`setAlertModal`のメソッドを`Methods`で設定します：
```    Javascript
methods: {
      ...mapMutations({
        setGeneModal: 'set_gene_modal',
        setAlertModal: 'set_alert_modal',
      }),
    },
```

気づくのが遅くて申し訳ありません！

2022-04-26 02:18 UTC, MarleenEliza commented on components/ScreenerView/ScreenerViewSample.vue
> +            });
ModalViewGeneと同様です。`...mapMutations`がimportされていない可能性があります。その場合は、Scriptタグ内に以下のようにImportできます。
```JavaScript
import { mapMutations } from 'vuex';
```

2022-04-26 02:18 UTC, MarleenEliza commented on components/search/SearchBar.vue
> +            });
ModalViewGeneと同様です。`...mapMutations`がimportされていない可能性があります。その場合は、Scriptタグ内に以下のようにImportできます。
```JavaScript
import { mapMutations } from 'vuex';

2022-04-26 02:18 UTC, MarleenEliza commented on components/ModalView/ModalViewGene.vue
>            .catch(function (error) {
細かいですが、`error`に`_`をつけた方が丁寧です。「変数を自動的に受け取るが、メソッド内に使わない」を表すためです。
```suggestion
          .catch(function (_error) {
```

2022-04-26 03:40 UTC, penqe approved these changes
ありがとうございます

2022-04-26 03:40 UTC, penqe commented on components/ModalView/ModalViewGene.vue
> +            });
詳細な説明ありがとうございます

2022-04-26 04:41 UTC, gstein314 commented
@MarleenEliza 
ありがとうございます。修正してみました。
ご確認の程、よろしくお願い致します。

2022-04-26 09:15 UTC, MarleenEliza approved these changes
ありがとうございます！

2022-04-26 09:16 UTC, merged