Add pagination to Project Results
dbcls/RefEx2 pull request #20
Opened 2022-05-12 01:16 UTC by neznayer

- Add pagination to `ProjectResults`
- Add `Items per page` setting to `Display settings`

2022-05-12 08:04 UTC, MarleenEliza requested changes
早速にありがとうございます！
基本的にいいと思いますが、コードのコメントと下記をご確認いただけますか？
1. Component名が今ProjectResultsPaginationとなっていますが、将来的にはIndexページにも使われる可能性があるため、ResultsPaginationに変更していただけますでしょうか？
2. すみませんが、丁度Devブランチが更新されたのでRebaseしてもらってもいいですか？もし解決方法がよく分からないConflict起きたら気軽にお知らせください！

2022-05-12 08:04 UTC, MarleenEliza commented on components/results/ProjectResultsPagination.vue
> +      font-size: 1.25rem
試してみる文字が少し大きい気がします。個人的にFont -sizeを設定しなくても良いと思いましたが、アントンさんはどう思いますか？

2022-05-13 06:06 UTC, neznayer commented on components/results/ProjectResultsPagination.vue
> +      font-size: 1.25rem
ありがとうございます！　個人的にもそう思いましたが、XDでは20px でしたので。
`font-size` をなくしました　🙇

2022-05-16 07:35 UTC, MarleenEliza requested changes
@neznayer ありがとうございます！コードはこれで問題ないと思います。

追加で一つお願いしたい点があります。Display settingsのデザインをもお願いできますでしょうか？
`ModalView/ModalViewDisplay`の componentの話です。
今まではDisplay settingsで表示すべきな項目を選ぶことしかできませんでしたが、今回はページの設定も追加していただいたと思います。機能が違うので項目名とItems per pageの間に少し空間があってもいい気がします。また、フォントをboldにしてみるのもありかもしれません。
`Columns to display`と`Items per page`のような二つのグループに分けてもいいかもしれません。アントンさんのデザインセンスにまけせますが、今のデザインが少しわかりにくい気がします。

<img width="324" alt="image" src="https://user-images.githubusercontent.com/62828450/168541071-166c6c00-d5c5-4506-bcdf-3d37f490c265.png">

2022-05-17 02:15 UTC, neznayer commented
@MarleenEliza お疲れ様です。
![Screen Shot 2022-05-17 at 11 12 17](https://user-images.githubusercontent.com/55772081/168714551-a0fb6d9d-ec06-4a07-b4dc-ec8d87ba6d5b.png)
少しいじりました、ご確認くださいください🙇‍♂️

2022-05-17 04:42 UTC, MarleenEliza commented
@neznayer ありがとうございます！
いいと思います！

（ちなみに私のコードではなくてぱっちさんのものです！）

2022-05-17 04:42 UTC, merged