Bugfix/UI improvement
dbcls/RefEx2 pull request #68
Opened 2022-09-06 05:56 UTC by maruk0chan

2022-09-06 08:01 UTC, maruk0chan commented
Some improvements aim to reduce the position change of components.
(Especially switching between filter 'gene' and 'sample')

2022-09-22 01:06 UTC, gstein314 requested changes

2022-09-22 01:06 UTC, gstein314 commented on pages/_organism/_project.vue
> +    label: 'log(TPM+1)',
2 is missing

2022-09-22 03:48 UTC, gstein314 commented
@maruk0chan 
Thank you.

2022-09-22 03:48 UTC, merged